
version: '{branch}-{build}'

install:
  - "SET PATH=C:\\Python36-x64;C:\\Python36-x64\\Scripts;%PATH%"
  - "python --version"
  - "pip install tox==2.9.1 virtualenv==15.1.0"

# Build the binary after tests
build: false

test_script:
  - "tox -e py27,py36 -- tests/unit"
  - ps: ".\\script\\build\\windows.ps1"

artifacts:
  - path: .\dist\docker-compose-Windows-x86_64.exe
    name: "Compose Windows binary"

deploy:
  - provider: Environment
    name: master-builds
    on:
      branch: master
