version = "unstable"
generator = "gogo"
plugins = ["grpc"]

# Control protoc include paths. Below are usually some good defaults, but feel
# free to try it without them if it works for your project.
[includes]
  # Paths that should be treated as include roots in relation to the vendor
  # directory. These will be calculated with the vendor directory nearest the
  # target package.
  #packages = ["github.com/gogo/protobuf", "github.com/gogo/googleapis"]

  # Paths that will be added untouched to the end of the includes. We use
  # `/usr/local/include` to pickup the common install location of protobuf.
  # This is the default.
  #after = ["/usr/local/include", "/usr/include"]

  vendored = ["github.com/gogo/protobuf", "github.com/gogo/googleapis"]

# This section maps protobuf imports to Go packages. These will become
# `-M` directives in the call to the go protobuf generator.
[packages]
  "gogoproto/gogo.proto" = "github.com/gogo/protobuf/gogoproto"
  "google/protobuf/any.proto" = "github.com/gogo/protobuf/types"
  "google/protobuf/empty.proto" = "github.com/gogo/protobuf/types"
  "google/protobuf/descriptor.proto" = "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
  "google/protobuf/field_mask.proto" = "github.com/gogo/protobuf/types"
  "google/protobuf/timestamp.proto" = "github.com/gogo/protobuf/types"
  "google/protobuf/duration.proto" = "github.com/gogo/protobuf/types"
  "google/rpc/status.proto" = "github.com/gogo/googleapis/google/rpc"
