version: 2
jobs:
  test:
    macos:
      xcode: "9.4.1"
    steps:
    - checkout
    - run:
        name: setup script
        command: ./script/setup/osx
    - run:
        name: install tox
        command: sudo pip install --upgrade tox==2.1.1 virtualenv==16.2.0
    - run:
        name: unit tests
        command: tox -e py27,py37 -- tests/unit

  build-osx-binary:
    macos:
      xcode: "9.4.1"
    steps:
      - checkout
      - run:
          name: upgrade python tools
          command: sudo pip install --upgrade pip virtualenv==16.2.0
      - run:
         name: setup script
         command: DEPLOYMENT_TARGET=10.11 ./script/setup/osx
      - run:
         name: build script
         command: ./script/build/osx
      - store_artifacts:
          path: dist/docker-compose-Darwin-x86_64
          destination: docker-compose-Darwin-x86_64
      - deploy:
          name: Deploy binary to bintray
          command: |
            OS_NAME=Darwin PKG_NAME=osx ./script/circle/bintray-deploy.sh

  build-linux-binary:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: build Linux binary
          command: ./script/build/linux
      - store_artifacts:
          path: dist/docker-compose-Linux-x86_64
          destination: docker-compose-Linux-x86_64
      - deploy:
          name: Deploy binary to bintray
          command: |
            OS_NAME=Linux PKG_NAME=linux ./script/circle/bintray-deploy.sh


workflows:
  version: 2
  all:
    jobs:
      - test
      - build-linux-binary
      - build-osx-binary
