name: dispatch release event to downstream repositories

on:
  workflow_dispatch:

jobs:
  dispatch_release_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_DOC_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'docker',
              repo: 'docker.github.io',
              workflow_id: 'compose_release',
              ref: 'compose-api-upstream',
              inputs: {
                release: ${{ GITHUB_REF }},
              },
            })
