name: Releaser

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag"
        required: true
env:
  GO_VERSION: 1.18.5
jobs:
  upload-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Setup docker CLI
        run: |
          curl https://download.docker.com/linux/static/stable/x86_64/docker-20.10.17.tgz | tar xz
          sudo cp ./docker/docker /usr/bin/ && rm -rf docker && docker version

      - name: Build
        run: make GIT_TAG=${{ github.event.inputs.tag }} -f builder.Makefile cross

      - name: Compute checksums
        run: cd bin; for f in *; do shasum --binary --algorithm 256 $f | tee -a checksums.txt > $f.sha256; done

      - name: License
        run: cp packaging/* bin/

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/*"
          generateReleaseNotes: true
          draft: true
          commit: "v2"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag }}
